[package]
name = "serde_hkx"
authors.workspace = true
version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true


[dependencies]
byteorder = "1.5.0"
educe = "0.6.0"
havok_serde = { path = "../crates/havok_serde" }
havok_types = { path = "../crates/havok_types", features = ["serde"] }
indexmap = "2.2.6"
num-derive = "0.4"                                                     # enum to number
num-traits = "0.2"
snafu = "0.8.2"                                                        # Define all error patterns(with backtrace)
static_assertions = "1.1.0"
tracing = { version = "0.1.40", optional = true }
zerocopy = "0.7.34"


[dev-dependencies]
bitflags = "2.4"                                   # To generate flags type
pretty_assertions = "1.4"                          # Color diff assertion
rhexdump = "0.2.0"
tracing_easy = { path = "../crates/tracing_easy" } # execute tracing(logger)

[features]
default = ["std", "tracing"]

# Provide derive(Serialize, Deserialize) macros.
# derive = ["havok_serde_derive"]

# Provide impls for common standard library types like Vec<T> and HashMap<K, V>.
# Requires a dependency on the Rust standard library.
std = []

# Provide impls for types in the Rust core allocation and collections library
# including Vec<T>, and Cow<T>. This is a subset of std but may
# be enabled without depending on all of std.
alloc = []

# Use tracing logging.(We may need `tracing-subscriber` crate too.)
tracing = ["dep:tracing"]
