[package]
name = "serde_hkx"
authors.workspace = true
version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true


[dependencies]
annotate-snippets = "0.11.4"                                              # Error reporting display
byteorder = "1.5.0"
educe = "0.6.0"
havok_serde = { path = "../crates/havok_serde", features = ["indexmap"] }
havok_types = { path = "../crates/havok_types" }
havok_types_derive = { path = "../crates/havok_types_derive" }            # To impl `Default`&`FromStr` for Bitflags
indexmap = "2.2.6"
rhexdump = "0.2.0"                                                        # hexdump display for binary error repoting
snafu = "0.8.2"                                                           # Define all error patterns(with backtrace)
static_assertions = "1.1.0"
tracing = { version = "0.1.40", optional = true }
winnow = { version = "0.6.8", features = ["simd"] }                       # Parser conbinator

[dev-dependencies]
bitflags = "2.4"                                             # To generate flags type(mock)
havok_classes = { path = "../crates/havok_classes" }
jwalk = { version = "0.8" }                                  # To enumarate json class files
num-derive = "0.4"                                           # enum to number(mock)
num-traits = "0.2"                                           # enum to number(mock)
pretty_assertions = "1.4"                                    # Color diff assertion
quick_tracing = { version = "0.1.5", features = ["derive"] }
tracing = { version = "0.1.40" }
zerocopy = { version = "0.7.34" }                            # To(As)Bytes

[features]
# default = []
default = ["tracing"]

# Use tracing logging.(We may need `tracing-subscriber` crate too.)
tracing = ["dep:tracing"]

# Derive `serde`
serde = ["havok_types/serde"]
